# -*- coding: utf-8 -*-
"""CS224W - Colab 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Aa0eKSmyYef1gORvlHv7EeQzSVRb30eL

# **CS224W - Colab 2**

In this Colab, we will construct our own graph neural network by using PyTorch Geometric (PyG) and apply the model on
two of Open Graph Benchmark (OGB) datasets. Those two datasets are used to benchmark the model performance on two
different graph-related tasks. One is node property prediction, predicting properties of single nodes.
Another one is graph property prediction, predicting the entire graphs or subgraphs.

At first, we will learn how PyTorch Geometric stores the graphs in PyTorch tensor.

We will then load and take a quick look on one of the Open Graph Benchmark (OGB) datasets by using the `ogb` package.
OGB is a collection of realistic, large-scale, and diverse benchmark datasets for machine learning on graphs.
The `ogb` package not only provides the data loader of the dataset but also the evaluator.

At last, we will build our own graph neural networks by using PyTorch Geometric. And then apply and evaluate the models
on node property prediction and grpah property prediction tasks.

**Note**: Make sure to **sequentially run all the cells in each section**, so that the intermediate
variables / packages will carry over to the next cell

Have fun on Colab 2 :)

# Device
You might need to use GPU for this Colab.

Please click `Runtime` and then `Change runtime type`. Then set the `hardware accelerator` to **GPU**.

# Installation
"""
# \Mina: this code was edited in a virtual env on Macbook Air 2022 with M2chip with installed packages.

# !pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
# !pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
# !pip install -q torch-geometric
# !pip install ogb

"""# 1 PyTorch Geometric (Datasets and Data)

PyTorch Geometric generally has two classes for storing or transforming the graphs into tensor format. 
One is the `torch_geometric.datasets`, which contains a variety of common graph datasets. 
Another one is `torch_geometric.data` that provides the data handling of graphs in PyTorch tensors.

In this section, we will learn how to use the `torch_geometric.datasets` and `torch_geometric.data`.

## PyG Datasets

The `torch_geometric.datasets` has many common graph datasets. Here we will explore the usage by using one 
example dataset.
"""

from torch_geometric.datasets import TUDataset

root = '/Users/mina/Documents/Academics/Data/Benchmarks/enzymes'
name = 'ENZYMES'

# The ENZYMES dataset
pyg_dataset = TUDataset('./enzymes', 'ENZYMES')

# You can find that there are 600 graphs in this dataset
print(pyg_dataset)

"""## Question 1: What is the number of classes and number of features in the ENZYMES dataset? (5 points)"""


def get_num_classes(pyg_dataset):
    # TODO: Implement this function that takes a PyG dataset object
    # and return the number of classes for that dataset.

    # num_classes = 0

    #  Your code here ######################
    num_classes = pyg_dataset.num_classes
    #########################################

    return num_classes


def get_num_features(pyg_dataset):
    # TODO: Implement this function that takes a PyG dataset object
    # and return the number of features for that dataset.

    # num_features = 0

    # Your code here ########################
    num_features = pyg_dataset.num_features
    #########################################

    return num_features

# You may find that some information need to be stored in the dataset level,
# specifically if there are multiple graphs in the dataset


num_classes = get_num_classes(pyg_dataset)
num_features = get_num_features(pyg_dataset)
print(f"{name} dataset has {num_classes} classes")
print(f"{name} dataset has {num_features} features")

"""## PyG Data

Each PyG dataset usually stores a list of `torch_geometric.data.Data` objects. Each `torch_geometric.data.Data` object 
usually represents a graph. You can easily get the `Data` object by indexing on the dataset.

For more information such as what will be stored in `Data` object, please refer to the [documentation]
(https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html#torch_geometric.data.Data).

## Question 2: What is the label of the graph (index 100 in the ENZYMES dataset)? (5 points)
"""


def get_graph_class(pyg_dataset, idx):
    # TODO: Implement this function that takes a PyG dataset object,
    # the index of the graph in dataset, and returns the class/label
    # of the graph (in integer).

    # label = -1
    # Your code here ########################
    label = pyg_dataset[idx].y
    #########################################

    return label


# Here pyg_dataset is a dataset for graph classification
graph_0 = pyg_dataset[0]
print(graph_0)
idx = 100
label = get_graph_class(pyg_dataset, idx)
print('Graph with index {} has label {}'.format(idx, label))

"""## Question 3: What is the number of edges for the graph (index 200 in the ENZYMES dataset)? (5 points)"""


def get_graph_num_edges(pyg_dataset, idx):
    # TODO: Implement this function that takes a PyG dataset object,
    # the index of the graph in dataset, and returns the number of
    # edges in the graph (in integer). You should not count an edge
    # twice if the graph is undirected. For example, in an undirected
    # graph G, if two nodes v and u are connected by an edge, this edge
    # should only be counted once.

    # num_edges = 0

    # Your code here ########################
    num_edges = pyg_dataset[idx].edge_index.shape[-1] / 2

    # Note:
    # 1. You can't return the data.num_edges directly
    # 2. We assume the graph is undirected
    # (~4 lines of code)

    #########################################

    return int(num_edges)


idx = 200
num_edges = get_graph_num_edges(pyg_dataset, idx)
print(f'Graph with index {idx} has {num_edges} edges')

"""# 2 Open Graph Benchmark (OGB)

The Open Graph Benchmark (OGB) is a collection of realistic, large-scale, and diverse benchmark datasets for 
machine learning on graphs. Its datasets are automatically downloaded, processed, and split using the OGB Data Loader. 
The model performance can also be evaluated by using the OGB Evaluator in a unified manner.

## Dataset and Data

OGB also supports the PyG dataset and data. Here we take a look on the `ogbn-arxiv` dataset.
"""

import torch_geometric.transforms as T
from ogb.nodeproppred import PygNodePropPredDataset

dataset_name = 'ogbn-arxiv'
# Load the dataset and transform it to sparse tensor
dataset = PygNodePropPredDataset(name=dataset_name,
                                 transform=T.ToSparseTensor())
print(f'The {dataset_name} dataset has {len(dataset)} graph')

# Extract the graph
data = dataset[0]
print(data)

"""## Question 4: What is the number of features in the ogbn-arxiv graph? (5 points)"""


def graph_num_features(data):
    # TODO: Implement this function that takes a PyG data object,
    # and returns the number of features in the graph (in integer).

    # num_features = 0

    # Your code here #######################
    # (~1 line of code)
    num_features = data.num_features
    #########################################

    return num_features

num_features = graph_num_features(data)
print('The graph has {} features'.format(num_features))

"""# 3 GNN: Node Property Prediction

In this section we will build our first graph neural network by using PyTorch Geometric and apply it on node property 
prediction (node classification).

We will build the graph neural network by using GCN operator 
([Kipf et al. (2017)](https://arxiv.org/pdf/1609.02907.pdf)).

You should use the PyG built-in `GCNConv` layer directly.

## Setup
"""

import torch
import torch.nn as t_nn
import torch.nn.functional as F
print(torch.__version__)

# The PyG built-in GCNConv
from torch_geometric.nn import GCNConv
import torch_geometric.nn as tg_nn

import torch_geometric.transforms as T
from ogb.nodeproppred import PygNodePropPredDataset, Evaluator

"""## Load and Preprocess the Dataset"""

dataset_name = 'ogbn-arxiv'
dataset = PygNodePropPredDataset(name=dataset_name, transform=T.ToSparseTensor())
data = dataset[0]

# Make the adjacency matrix to symmetric
data.adj_t = data.adj_t.to_symmetric()

# device = 'cuda' if torch.cuda.is_available() else 'cpu'
# device = torch.device('mps')
device = 'cpu'

# If you use GPU, the device should be cuda
print('Device: {}'.format(device))

data = data.to(device)
split_idx = dataset.get_idx_split()
train_idx = split_idx['train'].to(device)

"""## GCN Model

Now we will implement our GCN model!

Please follow the figure below to implement your `forward` function.


![test](https://drive.google.com/uc?id=128AuYAXNXGg7PIhJJ7e420DoPWKb-RtL)
"""


class GCN(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers, dropout, return_embeds=False):
        # TODO: Implement this function that initializes self.convs, 
        # self.bns, and self.softmax.

        super(GCN, self).__init__()



        # Your code here ########################
        # Note:
        # 1. You should use torch.nn.ModuleList for self.convs and self.bns
        # 2. self.convs has num_layers GCNConv layers
        # 3. self.bns has num_layers - 1 BatchNorm1d layers
        # 4. You should use torch.nn.LogSoftmax for self.softmax
        # 5. The parameters you can set for GCNConv include 'in_channels' and
        # 'out_channels'. More information please refer to the documentation:
        # https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.GCNConv
        # 6. The only parameter you need to set for BatchNorm1d is 'num_features'
        # More information please refer to the documentation:
        # https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm1d.html
        # (~10 lines of code)

        # A list of GCNConv layers
        self.num_layers = num_layers
        in_dims = [input_dim] + [hidden_dim for i in range(num_layers - 1)]
        out_dims = [hidden_dim for i in range(num_layers - 1)] + [output_dim]
        self.convs = torch.nn.ModuleList([GCNConv(i, o) for i, o in zip(in_dims, out_dims)])

        # A list of 1D batch normalization layers
        self.bns = torch.nn.ModuleList([t_nn.BatchNorm1d(i) for i in out_dims[:-1]])

        # The log softmax layer
        # self.softmax = F.log_softmax(x, dim=1)

        # the activation
        # self.activation = t_nn.ModuleList([t_nn.ReLU() for i in range(num_layers - 1)]) + \
        #                   t_nn.ModuleList([t_nn.Softmax()])

        #########################################

        # Probability of an element to be zeroed
        self.dropout = dropout

        # Skip classification layer and return node embeddings
        self.return_embeds = return_embeds

    def reset_parameters(self):
        for conv in self.convs:
            conv.reset_parameters()
        for bn in self.bns:
            bn.reset_parameters()

    def forward(self, x, adj_t):
        # TODO: Implement this function that takes the feature tensor x,
        # edge_index tensor adj_t and returns the output tensor as
        # shown in the figure.

        y = x
        # Your code here ########################
        # Note:
        # 1. Construct the network as showing in the figure
        # 2. torch.nn.functional.relu and torch.nn.functional.dropout are useful
        # More information please refer to the documentation:
        # https://pytorch.org/docs/stable/nn.functional.html
        # 3. Don't forget to set F.dropout training to self.training
        # 4. If return_embeds is True, then skip the last softmax layer
        # (~7 lines of code)
        for l in range(self.num_layers - 1):
            y = self.convs[l](y, adj_t)
            y = self.bns[l](y)
            y = F.relu(y)
            y = F.dropout(y, p=self.dropout)
        y = self.convs[l+1](y, adj_t)
        out = y if self.return_embeds else F.log_softmax(y, dim=1)

        #########################################

        return out


def train(model, data, train_idx, optimizer, loss_fn):
    # TODO: Implement this function that trains the model by 
    # using the given optimizer and loss_fn.
    model.train()
    loss = 0

    # Your code here ########################
    # Note:
    # 1. Zero grad the optimizer
    # 2. Feed the data into the model
    # 3. Slicing the model output and label by train_idx
    # 4. Feed the sliced output and label to loss_fn
    # (~4 lines of code)
    optimizer.zero_grad()
    out = model(data.x, data.adj_t)
    loss = loss_fn(out[train_idx, :], data.y[train_idx, 0])

    #########################################

    loss.backward()
    optimizer.step()

    return loss.item()

# Test function here
@torch.no_grad()
def test(model, data, split_idx, evaluator):
    # TODO: Implement this function that tests the model by 
    # using the given split_idx and evaluator.
    model.eval()

    # The output of model on all data

    # Your code here ########################
    # (~1 line of code)
    # Note:
    # 1. No index slicing here
    out = model(data.x, data.adj_t)
    #########################################

    y_pred = out.argmax(dim=-1, keepdim=True)

    train_acc = evaluator.eval({
        'y_true': data.y[split_idx['train']],
        'y_pred': y_pred[split_idx['train']],
    })['acc']
    valid_acc = evaluator.eval({
        'y_true': data.y[split_idx['valid']],
        'y_pred': y_pred[split_idx['valid']],
    })['acc']
    test_acc = evaluator.eval({
        'y_true': data.y[split_idx['test']],
        'y_pred': y_pred[split_idx['test']],
    })['acc']

    return train_acc, valid_acc, test_acc


# Please do not change the args
args = {
    'device': device,
    'num_layers': 3,
    'hidden_dim': 256,
    'dropout': 0.5,
    'lr': 0.01,
    'epochs': 100,
}
args

# input_dim, hidden_dim, output_dim, num_layers, dropout = data.num_features, args['hidden_dim'], \
#                                                          dataset.num_classes, args['num_layers'], args['dropout']

model = GCN(data.num_features, args['hidden_dim'],
            dataset.num_classes, args['num_layers'],
            args['dropout']).to(device)
evaluator = Evaluator(name='ogbn-arxiv')

out = model(data.x, data.adj_t)

import copy

# reset the parameters to initial random value
model.reset_parameters()

optimizer = torch.optim.Adam(model.parameters(), lr=args['lr'])
loss_fn = F.nll_loss

best_model = None
best_valid_acc = 0

for epoch in range(1, 1 + args["epochs"]):
  loss = train(model, data, train_idx, optimizer, loss_fn)
  result = test(model, data, split_idx, evaluator)
  train_acc, valid_acc, test_acc = result
  if valid_acc > best_valid_acc:
      best_valid_acc = valid_acc
      best_model = copy.deepcopy(model)
  print(f'Epoch: {epoch:02d}, '
        f'Loss: {loss:.4f}, '
        f'Train: {100 * train_acc:.2f}%, '
        f'Valid: {100 * valid_acc:.2f}% '
        f'Test: {100 * test_acc:.2f}%')

best_result = test(best_model, data, split_idx, evaluator)
train_acc, valid_acc, test_acc = best_result
print(f'Best model: '
      f'Train: {100 * train_acc:.2f}%, '
      f'Valid: {100 * valid_acc:.2f}% '
      f'Test: {100 * test_acc:.2f}%')

"""## Question 5: What are your `best_model` validation and test accuracy? Please report them on Gradescope. 
For example, for an accuracy such as 50.01%, just report 50.01 and please don't include the percent sign. (20 points)

# \Mina : Best model: Train: 71.01%, Valid: 70.27% Test: 69.76%

# 4 GNN: Graph Property Prediction

In this section we will create a graph neural network for graph property prediction (graph classification)

## Load and preprocess the dataset
"""

from ogb.graphproppred import PygGraphPropPredDataset, Evaluator
from torch_geometric.data import DataLoader
from tqdm.notebook import tqdm

# Load the dataset 
dataset = PygGraphPropPredDataset(name='ogbg-molhiv')

# device = 'cuda' if torch.cuda.is_available() else 'cpu'
device = 'cpu'
# print('Device: {}'.format(device))

split_idx = dataset.get_idx_split()

# Check task type
print('Task type: {}'.format(dataset.task_type))

# Load the data sets into dataloader
# We will train the graph classification task on a batch of 32 graphs
# Shuffle the order of graphs for training set
train_loader = DataLoader(dataset[split_idx["train"]], batch_size=32, shuffle=True, num_workers=0)
valid_loader = DataLoader(dataset[split_idx["valid"]], batch_size=32, shuffle=False, num_workers=0)
test_loader = DataLoader(dataset[split_idx["test"]], batch_size=32, shuffle=False, num_workers=0)

# Please do not change the args
args = {
    'device': device,
    'num_layers': 5,
    'hidden_dim': 256,
    'dropout': 0.5,
    'lr': 0.001,
    'epochs': 30,
}
args

"""## Graph Prediction Model

Now we will implement our GCN Graph Prediction model!

We will reuse the existing GCN model to generate `node_embeddings` and use  Global Pooling on the nodes to predict 
properties for the whole graph.
"""

from ogb.graphproppred.mol_encoder import AtomEncoder
from torch_geometric.nn import global_add_pool, global_mean_pool


# GCN to predict graph property
class GCN_Graph(torch.nn.Module):
    def __init__(self, hidden_dim, output_dim, num_layers, dropout):
        super(GCN_Graph, self).__init__()

        # Load encoders for Atoms in molecule graphs
        self.node_encoder = AtomEncoder(hidden_dim)

        # Node embedding model
        # Note that the input_dim and output_dim are set to hidden_dim
        self.gnn_node = GCN(hidden_dim, hidden_dim,
                            hidden_dim, num_layers, dropout, return_embeds=True)

        # Your code here ########################
        # Note:
        # 1. Initialize the self.pool to global mean pooling layer
        # More information please refer to the documentation:
        # https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#global-pooling-layers
        # (~1 line of code)
        self.pool = global_mean_pool
        #########################################

        # Output layer
        self.linear = torch.nn.Linear(hidden_dim, output_dim)

    def reset_parameters(self):
        self.gnn_node.reset_parameters()
        self.linear.reset_parameters()

    def forward(self, batched_data):
        # TODO: Implement this function that takes the input tensor batched_data,
        # returns a batched output tensor for each graph.
        x, edge_index, batch = batched_data.x, batched_data.edge_index, batched_data.batch
        embed = self.node_encoder(x)

        # Your code here ########################
        # Note:
        # 1. Construct node embeddings using existing GCN model
        # 2. Use global pooling layer to construct features for the whole graph
        # More information please refer to the documentation:
        # https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#global-pooling-layers
        # 3. Use a linear layer to predict the graph property
        # (~3 lines of code)
        out = self.gnn_node(embed, edge_index)
        out = self.pool(out, batch)
        out = self.linear(out)

        #########################################

        return out


def train(model, device, data_loader, optimizer, loss_fn):
    # TODO: Implement this function that trains the model by 
    # using the given optimizer and loss_fn.
    model.train()
    loss = 0

    for step, batch in enumerate(data_loader):
        batch = batch.to(device)

        if batch.x.shape[0] == 1 or batch.batch[-1] == 0:
            pass
        else:
            # ignore nan targets (unlabeled) when computing training loss.
            is_labeled = batch.y == batch.y

            # Your code here ########################
            # Note:
            # 1. Zero grad the optimizer
            # 2. Feed the data into the model
            # 3. Use `is_labeled` mask to filter output and labels
            # 4. You might change the type of label
            # 5. Feed the output and label to loss_fn
            # (~3 lines of code)
            optimizer.zero_grad()
            output = model(batch)
            target = batch.y[is_labeled].float()
            output_ = output[is_labeled].detach()
            target.requires_grad = True
            output_.requires_grad = True
            loss = loss_fn(output_, target)
            #########################################

            loss.backward()
            optimizer.step()

    return loss.item()


# The evaluation function
def eval_model(model, device, loader, evaluator):
    model.eval()
    y_true = []
    y_pred = []

    for step, batch in enumerate(loader):
        batch = batch.to(device)

        if batch.x.shape[0] == 1:
            pass
        else:
            with torch.no_grad():
                pred = model(batch)
                pred = torch.sigmoid(pred)
            y_true.append(batch.y.view(pred.shape).detach().cpu())
            y_pred.append(pred.detach().cpu())

    y_true = torch.cat(y_true, dim=0).numpy()
    y_pred = torch.cat(y_pred, dim=0).numpy()

    input_dict = {"y_true": y_true, "y_pred": y_pred}

    return evaluator.eval(input_dict)


# hidden_dim, output_dim, num_layers, dropout =
# args['hidden_dim'], dataset.num_tasks, args['num_layers'], args['dropout']
model = GCN_Graph(args['hidden_dim'], dataset.num_tasks, args['num_layers'], args['dropout']).to(device)
evaluator = Evaluator(name='ogbg-molhiv')

import copy

model.reset_parameters()

optimizer = torch.optim.Adam(model.parameters(), lr=args['lr'])
loss_fn = torch.nn.BCEWithLogitsLoss()

best_model = None
best_valid_acc = 0

for epoch in range(1, 1 + args["epochs"]):
    loss = train(model, device, train_loader, optimizer, loss_fn)

    train_result = eval_model(model, device, train_loader, evaluator)
    val_result = eval_model(model, device, valid_loader, evaluator)
    test_result = eval_model(model, device, test_loader, evaluator)

    train_acc, valid_acc, test_acc = train_result[dataset.eval_metric], \
                                     val_result[dataset.eval_metric], \
                                     test_result[dataset.eval_metric]
    if valid_acc > best_valid_acc:
        best_valid_acc = valid_acc
        best_model = copy.deepcopy(model)
    print(f'Epoch: {epoch:02d}, '
          f'Loss: {loss:.4f}, '
          f'Train acc: {100 * train_acc:.2f}%, '
          f'Valid acc: {100 * valid_acc:.2f}% '
          f'Test acc: {100 * test_acc:.2f}%')

train_acc = eval(best_model, device, train_loader, evaluator)[dataset.eval_metric]
valid_acc = eval(best_model, device, valid_loader, evaluator)[dataset.eval_metric]
test_acc = eval(best_model, device, test_loader, evaluator)[dataset.eval_metric]

print(f'Best model: '
      f'Train: {100 * train_acc:.2f}%, '
      f'Valid: {100 * valid_acc:.2f}% '
      f'Test: {100 * test_acc:.2f}%')

"""## Question 6: What are your `best_model` validation and test ROC-AUC score? Please report them on Gradescope. 
For example, for an ROC-AUC score such as 50.01%, just report 50.01 and please don't include the percent sign. 
(20 points)

## Question 7 (Optional): Experiment with other two global pooling layers other than mean pooling in Pytorch Geometric.
"""

"""
\Mina
the classes are super unbalanced, only 3% of the train set are from class '1'. I could not reach an AUC 
of larger than random.
"""

"""# Submission

In order to get credit, you must go submit your answers on Gradescope.

Also, you need to submit the `ipynb` file of Colab 2, by clicking `File` and `Download .ipynb`. Please make sure that 
your output of each cell is available in your `ipynb` file.
"""